<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Title>Umbraco Aura</Title>
    <Authors>Girish S;Phases</Authors>
    <Company>Umbraco Aura</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Girish-kl33/Umbraco-Aura</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Girish-kl33/Umbraco-Aura</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>umbraco</PackageTags>
  </PropertyGroup>
</Project>
